name = "thankyou-chores-staging"
compatibility_date = "2024-01-15"

[env.staging]
name = "thankyou-chores-staging"
compatibility_date = "2024-01-15"

[env.production]
name = "thankyou-chores-production"
compatibility_date = "2024-01-15"

# Build configuration
[build]
command = "npm run build"
destination = ".next"

# Environment variables (set these in Cloudflare dashboard)
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# SUPABASE_SERVICE_ROLE_KEY
# NEXTAUTH_SECRET
# NEXTAUTH_URL