name = "household-mvp-staging"
main = ".open-next/worker.js"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat"]

# ビルド設定
[build]
command = "npm run build:cloudflare"

# 静的アセット設定
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Staging環境設定
[env.staging]
name = "household-mvp-staging"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat"]

# Production環境設定
[env.production]
name = "household-mvp-production"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat"]

# Environment variables (set these in Cloudflare dashboard)
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
# SUPABASE_SECRET_KEY
# NEXTAUTH_SECRET
# NEXTAUTH_URL