name = "household-mvp-staging"
main = ".open-next/worker.js"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:cloudflare"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Staging Worker 設定
[env.staging]
name = "household-mvp-staging"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[env.production]
name = "household-mvp-production"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat"]

# Worker 実行時に必要な値だけを共通でセット
[vars]
ENABLE_PUSH_SUBSCRIPTIONS = "false"

[env.staging.vars]
ENABLE_PUSH_SUBSCRIPTIONS = "true"
# （必要なら）WEB_PUSH_PRIVATE_KEY は secret として登録する

  - NEXT_PUBLIC_* 系は .env.production のみ管理 → ビルド時に
    Next.js が取り込む。
  - Worker 側で ON/OFF を切り替えたいもの（BFF で使う
    ENABLE_PUSH_SUBSCRIPTIONS など）は [vars] で指定。
  - 秘密鍵 (WEB_PUSH_PRIVATE_KEY など) は Cloudflare Dashboard
    の Secret で管理し、wrangler.toml には書かない。