name = "household-mvp-staging"
main = ".open-next/worker.js"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat"]

# ビルド設定
[build]
command = "npm run build:cloudflare"

# 静的アセット設定
[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# Staging環境設定
[env.staging]
name = "household-mvp-staging"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat"]

# Staging環境の環境変数
[env.staging.vars]
NEXT_PUBLIC_SUPABASE_URL = "https://njbormsqqfwnzwbigxuh.supabase.co"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_vPz2uxg31O02baWjpcKJ1g_wN9OX3HN"
NEXT_PUBLIC_APP_URL = "https://mvp-staging.yutatokeshi.workers.dev"

# Production環境設定
[env.production]
name = "household-mvp-production"
compatibility_date = "2024-11-21"
compatibility_flags = ["nodejs_compat"]

# Environment variables (set via wrangler secret put or vars)
# Public variables (can be set via [vars])
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY
# NEXT_PUBLIC_APP_URL

# Secret variables (must be set via wrangler secret put)
# SUPABASE_SECRET_KEY

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://njbormsqqfwnzwbigxuh.supabase.co"
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_vPz2uxg31O02baWjpcKJ1g_wN9OX3HN"
NEXT_PUBLIC_APP_URL = "https://mvp-staging.yutatokeshi.workers.dev"