// .open-next/worker.js は build 後に生成されるため公式ドキュメントどおり ts-ignore を付与
// https://developers.cloudflare.com/workers/framework-guides/web-apps/nextjs/
// @ts-ignore: generated by OpenNext during build
import defaultWorker, {
  DOQueueHandler,
  DOShardedTagCache,
  BucketCachePurge,
} from '../.open-next/worker.js'
import { createBffApp } from '../src/bff/app'

const bff = createBffApp()

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge }

export default {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext) {
    const url = new URL(request.url)

    if (url.pathname.startsWith('/push/')) {
      return bff.fetch(request, env, ctx)
    }

    return defaultWorker.fetch(request, env, ctx)
  },
}
